### STAGE 1: Build ###
FROM maven:3-openjdk-11 AS MAVEN_BUILD
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/
RUN mvn package
### STAGE 2: Run ###
FROM openjdk:11
EXPOSE 8083
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/mock-api.jar /app/ 
ENTRYPOINT ["java","-jar","mock-api.jar"]