version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - 27017:27017
    
  mockapi:
    container_name: "mockapi"
    image: mock-api-image
    ports:
    - 8083:8083
    
  garageapi:
    image: garage-api-image
    container_name: "garageapi"
    ports:
    - 8080:8080
    links:
    - mongodb
    - mockapi
    depends_on:
    - mockapi
    


